### ISSUE TITLE
postordereval.py example does not work

### ISSUE THREAD

**Issue by aykutbulut** [coin-or/GiMPy#5]
When I run postordereval.py example I get the following error,

Traceback (most recent call last):
  File "postordereval.py", line 18, in <module>
    T.postordereval(True)
  File "build/bdist.linux-x86_64/egg/coinor/gimpy/tree.py", line 464, in postordereval
  File "build/bdist.linux-x86_64/egg/coinor/gimpy/tree.py", line 478, in postordereval
KeyError: 1

**Comment by tkralphs** [comment]
Thanks, this was definitely foobar'd. Should be fixed now.
