### ISSUE TITLE
simplex_test.py fails

### ISSUE THREAD

**Issue by aykutbulut** [coin-or/GiMPy#7]
When I run simplex_test.py I get the following,

Traceback (most recent call last):
  File "simplex_test.py", line 227, in <module>
    x, pulp_obj_value = solve(g)
  File "simplex_test.py", line 131, in solve
    p.solve(GLPK(msg = 0))
  File "/usr/local/lib/python2.7/dist-packages/PuLP-1.6.1-py2.7.egg/pulp/pulp.py", line 1643, in solve
    status = solver.actualSolve(self, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/PuLP-1.6.1-py2.7.egg/pulp/solvers.py", line 346, in actualSolve
    raise PulpSolverError("PuLP: cannot execute "+self.path)
pulp.solvers.PulpSolverError: PuLP: cannot execute glpsol

I re-installed Pulp and it did not solve the problem. Is this a Gimpy bug or Pulp? How to fix it?

**Comment by tkralphs** [comment]
Umm, the error message tells you exactly what the issue is :). I'm assuming you don't have glpk installed. I just changed the call to
```python
p.solve()
```
so it would use any available solver and it works fine.
